### ISSUE TITLE
GetTransaction:  err: failed to base58 decode data, data: , err: zero length string

### ISSUE THREAD

**Issue by omarkilani** [portto/solana-go-sdk#31]
I'm not able to GetTransaction on this tx:

3vbZQ1F4JjsfW5gbX76UxBcV3YQxiq9WYSJYP6xvHphymHrzE7W4dTgk4ND9iQHqeKTXqHDwt36CXYd7Hb37ZDKd

It works fine on explorer.solana.com.

I tried with v1.10.1.

Just opening an issue until I get a chance to debug it.

**Comment by yihau** [comment]
I have released v1.10.2 for this issue.
Thank for your reporting!
