### ISSUE TITLE
Can I call the smart contract directly? How should I call it

### ISSUE THREAD

**Issue by E0001** [portto/solana-go-sdk#35]
Can I call the smart contract directly? How should I call it

**Comment by yihau** [comment]
sure. It depends which program you are interacting with.
The main idea is to compose transaction if you want to call smart contract (in solana we called it `program`).
FYI
```
A transaction = many signatures + a message
A message = many instructions + recent blockhash
```
you can treat every instruction equals a function in the program.

you can take a look at 

https://github.com/solana-labs/example-helloworld
https://dev.to/cogoo/solana-how-to-send-custom-instructions-via-instruction-data-4g9g

to learn how to compose your own instruciton.

**Comment by panchuprodhan** [comment]
How do I call the Hello World function in rust from go-client? [https://github.com/solana-labs/example-helloworld](url)

**Comment by yihau** [comment]
Oh. I think I should add some examples for interacting with custom program!

**Comment by panchuprodhan** [comment]
Yes, that should be helpful!

**Comment by leecarney** [comment]
> Oh. I think I should add some examples for interacting with custom program!

That would be amazing thanks.

**Comment by KunPengRen** [comment]
Hi, is there anyone example to call a custom program available now? 
Or can I call a smart contract directly developed by anchor framework?

**Comment by yihau** [comment]
added three page for basic concept

https://portto.github.io/solana-go-sdk/programs/101/hello.html
https://portto.github.io/solana-go-sdk/programs/101/accounts.html
https://portto.github.io/solana-go-sdk/programs/101/data.html
