### ISSUE TITLE
Send transaction test (main.go) gets "Transaction signature verification failure"

### ISSUE THREAD

**Issue by aaetera** [portto/solana-go-sdk#38]
I'm trying to send transaction to api.devnet.solana.com via examples/tour/transfer-sol/main.go and always getting an error "Transaction signature verification failure". Solana response is : 
{"jsonrpc":"2.0","error":{"code":-32003,"message":"Transaction signature verification failure"},"id":1}
 What am I doing wrong?

**Comment by yihau** [comment]
Can't see your code. Just guessing your signer is wrong.
When you send a tx, there is must a fee payer should sign.
for a transfer instruction, there is another signer, `from`
Maybe you can check these two signer first.
