### ISSUE TITLE
Updating Token Metadata

### ISSUE THREAD

**Issue by weewey** [portto/solana-go-sdk#47]
Hi!

Thanks for your work in this library. Do you have support for updating the token metadata for the token metadata program?

If not, can you possibly offer me some directions. I can help with a PR.

**Comment by yihau** [comment]
released a new version and you can take a look here for update metadata example
https://github.com/portto/solana-go-sdk/blob/main/docs/_examples/program/metaplex/token-metadata/update-metadata/main.go

will support more mpl token metadata program instructions
