### ISSUE TITLE
type of TransactionCount in get_epoch_info is *uint64 

### ISSUE THREAD

**Issue by liuyangc3** [portto/solana-go-sdk#48]
Why use `*uint64`  instead of `uint64`?

**Comment by yihau** [comment]
json rpc docs says
```
transactionCount: <u64 | null>, total number of transactions processed without error since genesis
```

https://docs.solana.com/developing/clients/jsonrpc-api#getepochinfo

and code 

https://github.com/solana-labs/solana/blob/master/rpc/src/rpc.rs#L2484
https://github.com/solana-labs/solana/blob/master/sdk/src/epoch_info.rs#L22

I think it is a option value so I make it nullable

**Comment by liuyangc3** [comment]
> json rpc docs says
> 
> ```
> transactionCount: <u64 | null>, total number of transactions processed without error since genesis
> ```
> 
> https://docs.solana.com/developing/clients/jsonrpc-api#getepochinfo
> 
> and code
> 
> https://github.com/solana-labs/solana/blob/master/rpc/src/rpc.rs#L2484 https://github.com/solana-labs/solana/blob/master/sdk/src/epoch_info.rs#L22
> 
> I think it is a option value so I make it nullable

Thank you
