### ISSUE TITLE
 when the network is down

### ISSUE THREAD

**Issue by scottywm** [portto/solana-go-sdk#61]
Hey thanks for answering all my questions.

In my last question I asked you what would happen to all the existing transactions that are in the process of getting executed and then suddenly the network goes down?

HERE IS MY QUESTION

These transactions were already being processed before the network crashed so would these pending transactions get rolled back or would they partially execute, leaving the transmitter 5%, 10%, 15% or 50% out of pocket? Or would these transactions stay in pending status until the network is up again ?

I already know that if the network is down new transactions won't happen, but that was not what i was asking. I'm wanting to know about what would happen to existing transactions that are in the process of being executed.

I'm building a platform that enables people to buy items using tether (USDT) on the Solana blockchain and its absolutely paramount that I understand what will happen to pending transactions when the network goes down because I don't want my users to be out of pocket when the network goes down and then get sued by my users and be liable for thousands of dollars or even go to jail.

The Solana network has gone down like seven times in the last 12 months so I really need to know what will happen to the current pending transactions if this event would occur again. It's very important and I really need an answer to this question otherwise I'm going to have to just use another blockchain network, which i don't want to have to do.

Thanks

**Comment by yihau** [comment]
Solana doesn't have txpool like Ethereum. If your gets dropped unless someone resends it or it's never processed again.

**Comment by scottywm** [comment]
I don't understand what you are talking about.

All I'm asking is if the network goes down while transactions are being processed, what happens to those transactions?

**Comment by yihau** [comment]
> All I'm asking is if the network goes down while transactions are being processed, what happens to those transactions?

It is hard to answer it cuz there are lots of steps for a transaction to be processed. you can take a look at [here](https://jito-labs.medium.com/solana-validator-101-transaction-processing-90bcdc271143)

> Will they partially execute like 5% of the tokens get sent

no. the result is either success or fail

**Comment by scottywm** [comment]
Thanks 🙏🙏
I've got one more question.

How do I do an acid transaction to make sure that ALL of the transactions are sent and not only some?

**Comment by scottywm** [comment]
That is very good to know that the transaction will either fail or succeed, I'm relieved to learn this. thanks heaps :)

Also i implemented your advice on ACID transactions and it worked brilliantly so thanks again for that :)
