### ISSUE TITLE
sending multiple transactions as ACID transactions

### ISSUE THREAD

**Issue by scottywm** [portto/solana-go-sdk#62]
Hello again :)

I was just wondering, is there a way to do ACID transaction with your library?

For example, if I was to send tether tokens to addresses A and B from address C, could I do an ACID transaction to ensure that the tokens get sent to both address A and B otherwise the transaction would roll back if the one didn't succeed?

You guys should start billing me for all your time in answering all my questions ;)

thanks heaps

**Comment by yihau** [comment]
Transferring tokens is an instruction. You can pack them (transfer token to A and B) into the same transaction. If one of them fails, the whole transaction will fail as well.
