### ISSUE TITLE
Killing a transaction

### ISSUE THREAD

**Issue by scottywm** [portto/solana-go-sdk#63]
My last concern is transaction duration.

Normally transactions are very quick using Solana but could there ever be a time when for some reason a transaction is going to take a long time to complete and so in this case could we somehow kill the transaction ?

Cheers :)

**Comment by jchen42703** [comment]
Solana transactions cannot be cancelled.

**Comment by yihau** [comment]
all solana transactions follow https://docs.solana.com/developing/programming-model/runtime#compute-budget
I don' think you can have a tx take hours even minutes.
If you find your txs missing, there is a info you can take a look https://solanacookbook.com/guides/retrying-transactions.html#facts
