### ISSUE TITLE
Private key dependency 

### ISSUE THREAD

**Issue by rahulanand20** [portto/solana-go-sdk#65]
https://github.com/portto/solana-go-sdk/blob/3379219af14a083038c96118c7d1d7daa7e21232/docs/_examples/nft/mint-a-nft-with-master-edition-v2/main.go#L21

Sir, I'm actually thinking of moving to production with mainnet config. But if I do so when the buyer(aka feePayer) has to mint then he has to provide is private key as per the code.. But no buyer will wish to provide/expose the private key .

My question is how can I mint an NFT without taking/using the private key of feePayer.

But usage of public key is fine

**Comment by yihau** [comment]
a tx = signatures + a message

the main idea is that you compose the message and send to user for signing. when you compose the message, you don't need user's private key. you only need the pubkey.

**Comment by rahulanand20** [comment]
https://github.com/portto/solana-go-sdk/blob/3379219af14a083038c96118c7d1d7daa7e21232/docs/_examples/nft/mint-a-nft-with-master-edition-v2/main.go#L62

sir in this above line Signer is of type.Account and we will not be able to use feepayer.publickey in the as it belongs to the common 

if i try to remove Signer I'm getting this error
**"2022/07/13 13:40:52 failed to send tx, err: rpc response error: {"code":-32003,"message":"Transaction signature verification failure"}"**

**Comment by rahulanand20** [comment]
Can you please help with the above query

**Comment by rahulanand20** [comment]
any suggestion on the above issue?

**Comment by rahulanand20** [comment]
so it seems private key is mandatory to sign a transaction
