### ISSUE TITLE
Transaction simulation failed

### ISSUE THREAD

**Issue by ImagineYao** [portto/solana-go-sdk#68]
When I transfer USDT, I got an error Transaction simulation failed: _Error processing Instruction 0: custom program error: 0x1._
And by a way, if there is a method that I could decode my raw transaction?

Following is my raw transaction string:

412XQ6QVMhiYhk4pxhVbTEA7B1nd4YFDae4XStAdedoXJx1K3qngHJ2FpXJDj3emf7VdpoKbSEhNv5T24S44qwRCPnRZunUX61pyB1Qyues4Ym6S9SvMXre46RNEpyso55rrvzf6pvK8JNFcorgNr4fFTdMg3e8XHP8gDheoKkVJU5XRzs3Pb9uFS24mKHNnY5T97rHjKAsXSdCm8PTiXHzELZiZTCKRVaf6RgL5idHVhyy1LLBX9vtr5z2VeyA9UdMdbH3y5NEJqVyTmxWhd2MadcsDH2v9yRvGspJsCjnFVYVQag5R7gzqxF7TXJ8CdWLNGPC9pXj9PqNxp5VA1XU6Xyv8178wRwaJW1MGST28wdp7VknkitXzV8qnq1MGKB8rURpDHwoPrHBdWN15BhFJ1KJcM4UvuuvDHBw7Bfv3NacQN3eVS6Rscjc3ahMYN848Q4uV5ZHs8H7CP2QqhFqeafArXoRS72882iuvnmmHbCKoVkbBEmf8zb5cp7w42RNUSyu3ZsCcF5H9gNhdEHNURqovVuBRkSf2fWbntHpyUjPFE41MBummX

**Comment by yihau** [comment]
to create a token account, you need 0.00203928 SOL.

**Comment by ImagineYao** [comment]
> to create a token account, you need 0.00203928 SOL. seems you only have 0.00171288.

ok, thanks a lot
