### ISSUE TITLE
Transaction with different tokens

### ISSUE THREAD

**Issue by Qweder93** [portto/solana-go-sdk#7]
Hello, is there a way in current SDK version to send different tokens (besides SOL) by sending transactions?

**Comment by yihau** [comment]
yes. I think you can compose it in the current SDK.

**Comment by Qweder93** [comment]
could you please explain a bit what parameters should be changed in Create Raw Transaction so amount would be in different currency, in examples it looks like I can't configure it.

**Comment by yihau** [comment]
you need to change the instructions in the transaction.
If you are new in Solana, I think you could take look for the [account model](https://docs.solana.com/developing/programming-model/accounts).
It will help you to build the concept quickly.
The account in Solana is totally different from Ethereum.

The instruction step will like below:
1. use sysprog.CreateAccount instruction twice to create three accounts, one for mint and the others for token account.
2. use tokenprog.InitializeMint and tokenprog.InitializeAccount to init mint and token account (token holder)
3. use tokenprog.MintTo or tokenprog.MintToChecked to mint some test token to your token account.
4. now you can use tokenprog.Transfer or tokenprog.TransferChecked to transfer token

**Comment by Qweder93** [comment]
thanks, now it's a bit more clear, still there's 4-5 methods to call with lot of values, which I'm not sure what some of them should mean, there's no comments about what should it be in methods. Maybe you have some sort of example? Would appreciate much :)

**Comment by yihau** [comment]
I write some example in the [gitbook](https://app.gitbook.com/@yihau/s/solana-development-with-go/).
feel free to open another issue for question. 💪💪💪
