### ISSUE TITLE
Get last few transactions 

### ISSUE THREAD

**Issue by Joeyboy92** [portto/solana-go-sdk#72]
I like this API however there is one feature I can't seem to find, to get the last say 10 transactions of a particular wallet using it's public address.

I want to be able to retrieve the last 10 transactions at a time and paginate through them all.

Each transaction must have at least the transaction amount, receiver and sender addresses ect.

Is there such a feature in this library and if so could you refer me to it?

If it's not a feature of this library how can I query the Blockchain to access this data?

**Comment by yihau** [comment]
> Each transaction must have at least the transaction amount, receiver and sender addresses ect.

Solana has a totally different tx structure from other chains. you can take a look here https://solanacookbook.com/core-concepts/transactions.html#facts

If you would like to decode it, I recommend that read the structure first. a tldr version is that parse instructions to know the tx purpose.
