### ISSUE TITLE
Querying a wallets transactions

### ISSUE THREAD

**Issue by scottywm** [portto/solana-go-sdk#75]
Hey, a few days ago I asked how I can use your library to query the transactions for a given wallet and I didn't understand your answer.

I need to retrieve transactions for a wallet and paginate through them.

Can I use your library to do this and if so how?

**Comment by yihau** [comment]
https://portto.github.io/solana-go-sdk/rpc/get-signatures-for-address.html

**Comment by scottywm** [comment]
Hey, there is a fundamental problem with this link you provided.

This link you provided only enables you to paginate through the earlier occurring transactions starting from an earlier time as show below, NOTE THAT ITS USING BEFORE

		res, err := c.GetSignaturesForAddressWithConfig(
			context.Background(),
			target,
			rpc.GetSignaturesForAddressConfig{
				Before: "2nYnHvbVuwmYeara3VjoCt9uS8ZXrSra5DRK7QBT8i5acoBiSK3FQY2vsaDSJQ6QX5i1pkvyRRjL1oUATMLZEsqy",
				Limit:  3,
			},
		)

What I need to do is start from a transaction signature that occurred at a later time and paginate through the transactions that occurred after it as shown below, NOTE THAT I'M USING THE WORD AFTER

		res, err := c.GetSignaturesForAddressWithConfig(
			context.Background(),
			target,
			rpc.GetSignaturesForAddressConfig{
				After: "2nYnHvbVuwmYeara3VjoCt9uS8ZXrSra5DRK7QBT8i5acoBiSK3FQY2vsaDSJQ6QX5i1pkvyRRjL1oUATMLZEsqy",
				Limit:  3,
			},
		)

Is there a way I can paginate from latest transactions to earliest transactions ?

**Comment by scottywm** [comment]
Hey, thanks for the link above, its working good for me.

I'm using the wallet address to get the transaction signatures and then I use the transaction signatures to get the transactions, only the signatures property in the transactions is an array and it looks like the signature is encoded.

I use this line of code to get the transactions

tr, errTran := c.GetTransaction(context.Background(), signature)

How do I get the signature from this encoded signature value?

Thanks

**Comment by yihau** [comment]
signatures on explorer are base58 encoded string. lots of rpc do use them as well. if you do base58 decode, you will get a 64 bytes array. they are the same value, just represent by different text-encoded.

**Comment by scottywm** [comment]
Hey, when i use your library to get the transaction, I'm needing to find the senders address and the recipients address and I have been relying on the order in which the sender and receiver details are inside the field PostTokenBalances, as shown below.

tr, _ := c.GetTransaction(context.Background(), sig)

recipient := tr.Meta.PostTokenBalances[1].Owner
sender := tr.Meta.PostTokenBalances[0].Owner

The problem I'm having is that sometimes the order seems to change around and cause errors in my application.

How do I obtain the sender and receivers address in a way thats going to be reliable?

**Comment by yihau** [comment]
pre/post balance and pre/post token balance can only know the final result. if a tx is like A send B 100 token, B send C 100 token, you can only know A lost 100 and C get 100 but you don't have any idea B is the man in the middle. if you would like to know the detail, you need to parse instructions. for decoding an instruction, every program can define on their own way. you should take a look to the program

**Comment by scottywm** [comment]
Thanks 🙏🙏🙏🙏
