### ISSUE TITLE
Get mint address for a given address 

### ISSUE THREAD

**Issue by Joeyboy92** [portto/solana-go-sdk#77]
Hey I need a way of identifying what type of tokens the address is for so I need a way of querying a given public address to get it's mint address.

If I create a new client what method do I use to get the tokens mint address ?

c := client.NewClient(rpc.MainnetRPCEndpoint)

Thanks 👍

**Comment by scottywm** [comment]
Actually I need to know how to do this to.

I need to know how to identify what type of cryptocurrency the given public address belongs to and I need a way of identifying what token the given token address belongs to.

How can we do this?

**Comment by yihau** [comment]
you can take a look at https://github.com/portto/solana-go-sdk/blob/main/docs/_examples/client/get-token-account/main.go
the mint is included in the token account data.
