### ISSUE TITLE
Support for transactions v2

### ISSUE THREAD

**Issue by holykol** [portto/solana-go-sdk#82]
**description:** 
add support for sending and parsing versioned messages that already exist on devnet

**docs:**
Solana proposal: https://docs.solana.com/proposals/transactions-v2#versioned-transactions
Rust SDK reference type: https://docs.rs/solana-sdk/latest/solana_sdk/message/enum.VersionedMessage.html

**abstract implementation steps:**
1. understand when new message version is encoded (if most upper bit of `num_required_signatures` is set afaik)
2. parse new message fields
3. serialize new version

**backwards compatibility concerns:** 
* do we keep new version backwards compatible or this is going to be new major version of the library?
* or do we add new types and methods like `types.DeserializeVersionedMessage([]byte) (MessageV2, error)`?
* current version fails to parse new transactions with confusing error messages. Should old methods just return error when they detect newer transaction versions?

**Comment by holykol** [comment]
@yihau willing to work on this, if no one else is interested

**Comment by yihau** [comment]
thank you! I just added a PR for this #86 will merge and release soon. maybe you can take a look and give me some feedback? I'm happy to make this SDK more easy to use.
